all: shell_integration get_utils

shell_integration:
	curl -L https://iterm2.com/shell_integration/bash -o iterm2_shell_integration.bash

get_utils:
	git clone https://github.com/gnachman/iterm2-website.git
